site_name: TaxonKit - NCBI Taxonomy Toolkit
pages:
- Home: index.md
- Download: download.md
- Usage: usage.md
- Tutorial: tutorial.md
- Benchmark: /bench/
- Taxid-Changelog: https://github.com/shenwei356/taxid-changelog
- More tools: https://github.com/shenwei356

theme:
    name: material
    palette:
        primary: cyan
        accent: blue grey
    icon:
        logon: material/school
    favicon: files/favicon.ico
    feature:
        tabs: false
extra:
  manifest: manifest.webmanifest
  
arkdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: false
  - toc:
      permalink:  Link

repo_url: https://github.com/shenwei356/taxonkit
site_description: TaxonKit - NCBI Taxonomy Toolkit
site_author: shenwei356
google_analytics: ['UA-28948626-9', 'bioinf.shenwei.me/taxonkit']
